import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Search Engine Google",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
